set(CPACK_PACKAGE_NAME "device-tester")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/mathisloge/device-tester")
set(CPACK_PACKAGE_EXECUTABLES "device-tester;device-tester")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE.txt")
set(CPACK_TOPLEVEL_TAG "device-tester")
set(CPACK_PACKAGE_VENDOR "Mathis Logemann")
set(CPACK_WIX_UPGRADE_GUID "249ca838-d0b2-4559-bf92-6d458868d86f")

if(WIN32)
    set(CPACK_GENERATOR "WIX")
elseif(UNIX AND NOT APPLE)
    set(CPACK_GENERATOR "DEB")
else()
    set(CPACK_GENERATOR "DragNDrop")  
endif()
include(CPack)
